spring:
  application:
    name: graphQL

  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:mysql://locahost:3306/storeDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update



